jaydhanani36@yahoo.com
jaydhanani36.jd@gmail.com
jaydhanani36@yahoo.com To priyamj At 04/08/2019 06:33:05
jaydhanani36.jd@gmail.com To priyamj At 04/08/2019 06:33:08
jaydhanani36.jd@gmail.com To Guest Guest At 04/08/2019 06:50:05
jaydhanani36@yahoo.com To jayd At 04/08/2019 07:03:04
jaydhanani36@yahoo.com To Guest Guest At 04/08/2019 07:05:05
shetadarshan@gmail.com To Guest Guest At 04/08/2019 09:54:05
Exception while running run() in 'scripts.monitor_price'
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/env/lib/python3.6/site-packages/django_extensions/management/email_notifications.py", line 65, in run_from_argv
    super(EmailNotificationCommand, self).run_from_argv(argv)
  File "/home/ubuntu/env/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/env/lib/python3.6/site-packages/django_extensions/management/email_notifications.py", line 77, in execute
    super(EmailNotificationCommand, self).execute(*args, **options)
  File "/home/ubuntu/env/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/env/lib/python3.6/site-packages/django_extensions/management/utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
  File "/home/ubuntu/env/lib/python3.6/site-packages/django_extensions/management/commands/runscript.py", line 242, in handle
    run_script(mod, *script_args)
  File "/home/ubuntu/env/lib/python3.6/site-packages/django_extensions/management/commands/runscript.py", line 148, in run_script
    mod.run(*script_args)
  File "/home/ubuntu/TrackPrice/src/scripts/monitor_price.py", line 21, in run
    if(send_mail(emails,URL,name,required_price)):
  File "/home/ubuntu/TrackPrice/src/scripts/monitor_price.py", line 73, in send_mail
    msg['To'] 			= 	formataddr(('Recipient', emails))
  File "/usr/lib/python3.6/email/utils.py", line 91, in formataddr
    address.encode('ascii')
AttributeError: 'list' object has no attribute 'encode'
Exception while running run() in 'scripts.monitor_price'
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/env/lib/python3.6/site-packages/django_extensions/management/email_notifications.py", line 65, in run_from_argv
    super(EmailNotificationCommand, self).run_from_argv(argv)
  File "/home/ubuntu/env/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/env/lib/python3.6/site-packages/django_extensions/management/email_notifications.py", line 77, in execute
    super(EmailNotificationCommand, self).execute(*args, **options)
  File "/home/ubuntu/env/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/env/lib/python3.6/site-packages/django_extensions/management/utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
  File "/home/ubuntu/env/lib/python3.6/site-packages/django_extensions/management/commands/runscript.py", line 242, in handle
    run_script(mod, *script_args)
  File "/home/ubuntu/env/lib/python3.6/site-packages/django_extensions/management/commands/runscript.py", line 148, in run_script
    mod.run(*script_args)
  File "/home/ubuntu/TrackPrice/src/scripts/monitor_price.py", line 21, in run
    if(send_mail(emails,URL,name,required_price)):
  File "/home/ubuntu/TrackPrice/src/scripts/monitor_price.py", line 73, in send_mail
    msg['To'] 			= 	formataddr(('Recipient', emails))
  File "/usr/lib/python3.6/email/utils.py", line 91, in formataddr
    address.encode('ascii')
AttributeError: 'list' object has no attribute 'encode'
Exception while running run() in 'scripts.monitor_price'
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/env/lib/python3.6/site-packages/django_extensions/management/email_notifications.py", line 65, in run_from_argv
    super(EmailNotificationCommand, self).run_from_argv(argv)
  File "/home/ubuntu/env/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/env/lib/python3.6/site-packages/django_extensions/management/email_notifications.py", line 77, in execute
    super(EmailNotificationCommand, self).execute(*args, **options)
  File "/home/ubuntu/env/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/env/lib/python3.6/site-packages/django_extensions/management/utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
  File "/home/ubuntu/env/lib/python3.6/site-packages/django_extensions/management/commands/runscript.py", line 242, in handle
    run_script(mod, *script_args)
  File "/home/ubuntu/env/lib/python3.6/site-packages/django_extensions/management/commands/runscript.py", line 148, in run_script
    mod.run(*script_args)
  File "/home/ubuntu/TrackPrice/src/scripts/monitor_price.py", line 21, in run
    if(send_mail(emails,URL,name,required_price)):
  File "/home/ubuntu/TrackPrice/src/scripts/monitor_price.py", line 73, in send_mail
    msg['To'] 			= 	formataddr(('Recipient', emails))
  File "/usr/lib/python3.6/email/utils.py", line 91, in formataddr
    address.encode('ascii')
AttributeError: 'list' object has no attribute 'encode'
